
% MATLAB Code from Sensor Array Analyzer App

% Generated by MATLAB 25.1 and Phased Array System Toolbox 25.1

% Generated on 13-Aug-2026 23:17:53

% Create a Uniform Linear Array Object
Array = phased.ULA('NumElements',6,...
    'ArrayAxis','x');
Array.ElementSpacing = 0.15;
Array.Taper = ones(1,6).';

% Create an isotropic antenna element
Elem = phased.IsotropicAntennaElement;
Elem.FrequencyRange = [0 1000000000];
Array.Element = Elem;

% Assign Frequencies and Propagation Speed
Frequency = 1000000000;
PropagationSpeed = 300000000;

% Assign Steering Angles
SteeringAngles = [0;0];

% Create Figure

% Plot Array Geometry
figure;
viewArray(Array,'ShowNormals',false,...
    'ShowTaper',false,'ShowIndex','None',...
    'ShowLocalCoordinates',true,'ShowAnnotation',false,...
    'Orientation',[0;0;0]);

% Calculate Steering Weights

Freq3D = 1000000000;
% Find the weights
w = ones(getNumElements(Array), length(Frequency));

% Plot 3d graph
format = 'polar';
plotType = 'Directivity';
figure;
pattern(Array, Freq3D , 'PropagationSpeed', PropagationSpeed,...
    'CoordinateSystem', format,'weights', w(:,1),...
    'ShowArray',false,'ShowLocalCoordinates',true,...
    'ShowColorbar',true,'Orientation',[0;0;0],...
    'Type', plotType);

% Find the weights
w = ones(getNumElements(Array), length(Frequency));

% Plot 2d azimuth graph
format = 'polar';
cutAngle = 0;
plotType = 'Directivity';
plotStyle = 'Overlay';
figure;
pattern(Array, Frequency, -180:180, cutAngle, 'PropagationSpeed', PropagationSpeed,...
    'CoordinateSystem', format ,'weights', w, ...
    'Type', plotType, 'PlotStyle', plotStyle);

% Plot Grating Lobe Diagram
figure;
plotGratingLobeDiagram(Array,Frequency(1),SteeringAngles(:,1),PropagationSpeed);
